// Florida DOR (Dept. of Revenue) property USE CODES — the statewide-standard
// land-use classification every county appraiser reports. The first 2 digits are
// uniform statewide; counties format the full code differently (4-digit "4830",
// 5-digit "04800", 2-digit "48") and append a county sub-code. We classify on the
// standard 2-digit base.
// Reference: Florida DOR Form DR-493 / s.195.073 F.S. property use codes.
export const DOR_USE_CODES: Record<string, string> = {
  "00": "Vacant residential",
  "01": "Single family",
  "02": "Mobile home",
  "03": "Multi-family (10+ units)",
  "04": "Condominium",
  "05": "Cooperative",
  "06": "Retirement home",
  "07": "Misc. residential",
  "08": "Multi-family (<10 units)",
  "09": "Residential common area",
  "10": "Vacant commercial",
  "11": "Stores, one story",
  "12": "Mixed use (store/office/residential)",
  "13": "Department store",
  "14": "Supermarket",
  "15": "Regional shopping mall",
  "16": "Community shopping center",
  "17": "Office, one story",
  "18": "Office, multi-story",
  "19": "Professional service building",
  "20": "Airport / marina / terminal",
  "21": "Restaurant / cafeteria",
  "22": "Drive-in restaurant",
  "23": "Financial institution",
  "24": "Insurance office",
  "25": "Repair service shop",
  "26": "Service station",
  "27": "Auto sales / repair / storage",
  "28": "Parking lot / mobile home park",
  "29": "Wholesale outlet / produce house",
  "30": "Florist / greenhouse",
  "31": "Drive-in theater / open stadium",
  "32": "Enclosed theater / auditorium",
  "33": "Nightclub / bar",
  "34": "Bowling / skating / arena",
  "35": "Tourist attraction",
  "36": "Camp",
  "37": "Race track",
  "38": "Golf course / driving range",
  "39": "Hotel / motel",
  "40": "Vacant industrial",
  "41": "Light manufacturing",
  "42": "Heavy industrial",
  "43": "Lumber yard / sawmill",
  "44": "Packing plant",
  "45": "Cannery / bottler / brewery",
  "46": "Food processing",
  "47": "Mineral processing",
  "48": "Warehouse / distribution / trucking",
  "49": "Open storage / junk yard",
  "50": "Improved agricultural",
  "51": "Cropland",
  "52": "Cropland",
  "53": "Cropland",
  "54": "Timberland",
  "55": "Timberland",
  "56": "Timberland",
  "57": "Timberland",
  "58": "Timberland",
  "59": "Timberland",
  "60": "Grazing land",
  "61": "Grazing land",
  "62": "Grazing land",
  "63": "Grazing land",
  "64": "Grazing land",
  "65": "Grazing land",
  "66": "Orchard / citrus grove",
  "67": "Poultry / bees / fish",
  "68": "Dairy / feed lot",
  "69": "Ornamental / misc. agricultural",
  "70": "Vacant institutional",
  "71": "Church",
  "72": "Private school / college",
  "73": "Private hospital",
  "74": "Home for the aged",
  "75": "Non-profit service / orphanage",
  "76": "Mortuary / cemetery",
  "77": "Club / lodge / union hall",
  "78": "Sanitarium / convalescent home",
  "79": "Cultural organization",
  "80": "Vacant governmental",
  "81": "Military",
  "82": "Forest / park / recreational",
  "83": "Public school",
  "84": "Public college",
  "85": "Public hospital",
  "86": "County (non-municipal govt)",
  "87": "State",
  "88": "Federal",
  "89": "Municipal",
  "90": "Leasehold interest (govt-owned)",
  "91": "Utility (electric/gas/phone)",
  "92": "Mining / petroleum / gas",
  "93": "Subsurface rights",
  "94": "Right-of-way",
  "95": "River / lake / submerged land",
  "96": "Sewage / waste land",
  "97": "Outdoor recreational / park",
  "98": "Centrally assessed",
  "99": "Acreage not zoned agricultural",
}

/** The standard 2-digit DOR class from any county's formatting (e.g. "04800" -> "48"). */
export function dorClass(code: string | null | undefined): string | null {
  if (!code) return null
  const digits = String(code).replace(/\D/g, "")
  if (!digits) return null
  const base = digits.slice(-4).slice(0, 2) // last-4 strips Pasco's leading 0, then first 2
  return base.padStart(2, "0")
}

/** Plain-English label for a DOR use code, or null if unknown. */
export function dorLabel(code: string | null | undefined): string | null {
  const cls = dorClass(code)
  return cls ? (DOR_USE_CODES[cls] ?? null) : null
}
