-- 2026-09-02: Pasco Property Appraiser easement type codes (ETYPE) -> labels.
-- The service publishes no coded-value domain; the labels live only in the
-- renderer of Easements/MapServer/{0..3} (uniqueValueInfos), read the same day.
-- Applied via MCP right after 20260902120000.

begin;

insert into gis.pasco_easement_types (code, label) values
  (0, 'Other'),
  (1, 'Amenity'),
  (2, 'Common Area'),
  (3, 'Conservation'),
  (4, 'Drainage'),
  (5, 'Drainage/ Access'),
  (6, 'Drainage/ Operation & Maintenance'),
  (7, 'Emergency Access'),
  (8, 'Flood Plain'),
  (9, 'Florida Power'),
  (10, 'Ingress/ Egress'),
  (11, 'Landscape'),
  (12, 'Landscape/ Wall'),
  (13, 'Lift Station'),
  (14, 'Park'),
  (15, 'Perpetual'),
  (16, 'Progress Energy'),
  (17, 'Pump Station'),
  (18, 'ROW'),
  (19, 'S.W.F.W.M.D.'),
  (20, 'Sewage Station'),
  (21, 'Temporary'),
  (22, 'Upland'),
  (23, 'Utility'),
  (24, 'Verizon'),
  (25, 'Well Site'),
  (26, 'Wetland Buffer'),
  (27, 'Wetland Conservation'),
  (28, 'Tampa Electric Company'),
  (29, 'Typical Guy'),
  (30, 'Buffer'),
  (31, 'Retention'),
  (32, 'Exclusive'),
  (33, 'Open Space'),
  (34, 'GTE Florida INC'),
  (35, 'With'),
  (36, 'Withlacoochee River Electric'),
  (37, 'Wall'),
  (38, 'Access'),
  (39, 'Sovereign Submerged Lands'),
  (40, 'Fence'),
  (41, 'Mitigation'),
  (42, 'Private Open Space & Park'),
  (43, 'Billboard'),
  (44, 'Private Open Space & Landscape'),
  (45, 'Pedestrian'),
  (46, 'Communication'),
  (47, 'Wetland Mitigation'),
  (48, 'Type "D"'),
  (49, 'Fence/Maintenance'),
  (50, 'Flood Plain & Wetland Mitigation Site'),
  (51, 'Wetland Conservation Area/Mitigation Area'),
  (52, 'Electric Power'),
  (53, 'Private Ingress/Egress'),
  (54, 'Wall/Fence'),
  (55, 'Water Meter'),
  (56, 'Irrigation'),
  (57, 'Force Main'),
  (58, 'Type "A"'),
  (59, 'Private Open Space'),
  (60, 'Wildlife Crossing'),
  (61, 'Sidewalk'),
  (62, 'Green Belt'),
  (63, 'Screened Buffer'),
  (64, 'Drainage Mitigation'),
  (65, 'Secondary Access Road'),
  (66, 'Building Setback'),
  (67, 'Building Encroachment'),
  (68, 'Drive'),
  (69, 'Mutual Access'),
  (70, 'Sewer'),
  (71, 'Sign'),
  (72, 'Pipe'),
  (73, 'Electric'),
  (74, 'Public'),
  (75, 'Upland Buffer'),
  (76, 'A/C Drain Pipe Maintenance'),
  (77, 'Slope'),
  (78, 'Pipeline'),
  (79, 'Transmission'),
  (80, 'Upland Conservation'),
  (81, 'Recreation Area'),
  (82, 'U.S. Army Corps Of Engineers/Perpetual Conservation Easement'),
  (83, 'F.D.O.T. Drainage'),
  (85, 'Conservation/Drainage'),
  (86, 'Preservation'),
  (87, 'Landscaped Common Area'),
  (88, 'Buffer/Drainage'),
  (89, 'Preservation Area Wetland Conservation Area'),
  (90, 'Passive Recreation Area'),
  (91, 'Upland Preservation'),
  (92, 'Conservation/Preservation'),
  (93, 'C.O.E. Jurisdictional Area'),
  (94, 'Preservation & Drainage'),
  (95, 'Reclaim Water Main'),
  (96, 'Sanitary & Water Main'),
  (97, 'Fountain Vault'),
  (98, 'Flagpole'),
  (99, 'Surface Water Area'),
  (100, 'Cross Access'),
  (101, 'Water'),
  (102, 'West Coast Regional Water Supply Authority'),
  (103, 'Airport'),
  (104, 'Parking Lot'),
  (106, 'Jurisdictional'),
  (107, 'GTE'),
  (108, 'H.O.A.'),
  (109, 'Maintenance'),
  (110, 'Fire Line'),
  (111, 'Sanitary'),
  (112, 'Neighborhood Park'),
  (113, 'Flood Plain Compensation'),
  (114, 'Submerged Lands'),
  (115, 'Boardwalk'),
  (116, 'Withlacoochee River Electric Cooperative'),
  (117, 'Telephone'),
  (118, 'Cross Parking'),
  (119, 'Corner'),
  (120, 'Permanent Monitor Well Easement'),
  (121, 'Buffer Wall/Sign/Landscape'),
  (122, 'Stormwater'),
  (123, 'Water Main'),
  (124, 'Cart Path'),
  (125, 'Gasline'),
  (126, 'Buffer Wall/Fence'),
  (127, 'Wetland Conservation/Preservation'),
  (128, 'Conservation/Mitigation'),
  (129, 'Distribution'),
  (130, 'Guying'),
  (131, 'Air and Light'),
  (132, 'Canal Maintenance'),
  (133, 'SWM Facilities'),
  (134, 'Sight Control'),
  (135, 'Dumpster Site'),
  (136, 'Golf Cart Path'),
  (137, 'Green'),
  (138, 'Swale'),
  (139, 'Type "B"'),
  (140, 'Septic Tank'),
  (141, 'Reciprocal'),
  (142, 'Potable Water'),
  (143, 'Wastewater'),
  (144, 'Cable Television'),
  (145, 'Wetland'),
  (146, 'Detention/Conservation'),
  (147, 'Drainage/ROW'),
  (148, 'Navigational'),
  (149, 'Water Transmission'),
  (150, 'Cathodic System'),
  (151, 'Monopole'),
  (152, 'Green Area'),
  (153, 'Screening'),
  (154, 'Firetruck Turnaround'),
  (155, 'Clear Sight'),
  (156, 'Retention Wall'),
  (157, 'Private ROW'),
  (158, 'Fire Hydrant'),
  (159, 'Transformer'),
  (160, 'Landscape Buffer'),
  (161, 'Restrictive'),
  (162, 'Building Maintenance'),
  (163, 'Overhang Encroachment'),
  (164, 'Canal ROW'),
  (165, 'Perpetual Flood Plain Mitigation'),
  (166, 'Sanitary Sewer'),
  (167, 'Railroad Line Service'),
  (168, 'Right of Way Overhanging'),
  (169, 'Power Line'),
  (170, 'Golf Course'),
  (171, 'Gravity Lines'),
  (172, 'Manhole'),
  (173, 'Miscellaneous Water & Sewer Lines'),
  (174, 'Water Line'),
  (175, 'Water Tank'),
  (176, 'Water Connection'),
  (177, 'Easement'),
  (178, 'Mobile Home'),
  (179, 'Guard Shack'),
  (180, 'Power Company'),
  (181, 'Traffic Control'),
  (182, 'Natural Area'),
  (183, 'Monitor Well'),
  (184, 'Withlacoochee Power'),
  (185, 'Temporary Construction'),
  (186, 'Heidorn Development'),
  (187, 'Pool'),
  (188, 'Drainage/ Outfall Ditch'),
  (189, 'Marina'),
  (190, 'Power'),
  (191, 'Signalization'),
  (192, 'No Improvements'),
  (193, 'Access/Garage'),
  (194, 'Landscape/Gate'),
  (195, 'Wall Buffer'),
  (196, 'Storm Sewer'),
  (197, 'Mosquito Control'),
  (198, 'Security Wall'),
  (199, 'Sewer Line'),
  (200, 'Drainage Retention Area'),
  (201, 'Telephone Distribution'),
  (202, 'Access/Visibility'),
  (203, 'Tower'),
  (204, 'Sewer Main'),
  (205, 'Waterway'),
  (206, 'Boat Lift'),
  (207, 'Bike Path'),
  (208, 'Landscape/Nonliving Buffer'),
  (209, 'Yard'),
  (210, 'Eave'),
  (211, 'Buffer Wall'),
  (212, 'Water Distribution'),
  (213, 'Wetland Jurisdictional'),
  (214, 'Drainage Buffer'),
  (215, 'ROW Buffer'),
  (216, 'Land Use Buffer'),
  (217, 'Reclaimed Water Pipe'),
  (218, 'Nature Walk'),
  (219, 'Landscape/Wall/Signl'),
  (220, 'Landscape/Wall/Sign'),
  (221, 'Wall/Landscape/Access/Trail'),
  (222, 'Landscape/Wall/Sidewalk/Sign'),
  (223, 'Landscape/Sidewalk'),
  (224, 'Buffer/Sign/Landscape'),
  (225, 'Harmonizing'),
  (226, 'Buffer/Sidewalk'),
  (227, 'Buffer/Sidewalk/Bike Path'),
  (228, 'Open Space/Sidewalk/Bike Path'),
  (229, 'Open Space/Access'),
  (230, 'Buffer/Access'),
  (231, 'Sidewalk/Bike Path'),
  (232, 'Ingress/ Egress/Open Space/Conservation'),
  (233, 'Guy Wire'),
  (234, 'Landscape Buffer/Access'),
  (235, 'Ingress/ Egress/Sanitary & Water Main'),
  (236, 'Wetland Conservation/'),
  (237, 'Wetland Conservation/Recreational'),
  (238, 'Park/Clubhouse'),
  (239, 'Landscape/ Wall/Slope'),
  (240, 'Wildlife Corridor/Conservation'),
  (241, 'Operation'),
  (242, 'Ingress/ Egress/Open Space'),
  (243, 'Ingress/ Egress/ Open Space'),
  (244, 'Parking'),
  (245, 'Lake'),
  (246, 'Flood Mitigation'),
  (247, 'Uplands Mitigation'),
  (248, 'Wetlands Preservation'),
  (249, 'Landscape/Buffer/Drainage/Utility'),
  (250, 'Conservation Buffer'),
  (251, 'Drainage/Utility'),
  (252, 'Perpetual Right Of Way'),
  (253, 'Monitor Well Site'),
  (254, 'Well Setback'),
  (255, 'Common Area/ Landscape/ Pedestrian Access'),
  (256, 'Common Area/ Drainage/ Landscape/ Pedestrian Access'),
  (257, 'Drainage/ Landscape/ Pedestrian')
on conflict (code) do update set label = excluded.label;

commit;
